### ISSUE TITLE
Investigate the message "The PKP PLN does not know about this journal yet"

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkppln#8]
**Describe the bug**
Journals have been seeing the message `The PKP PLN does not know about this journal yet`, but the staging server is configured to accept/allow journals by default.

**Expected behavior**
The journal should be allowed to deposit as soon as it completes all the requirements and is accessible externally (not under a firewall/local network).

**Comment by jonasraoni** [comment]
Some journals are failing to pass through the `ping` due to invalid output:
- Empty space before the XML prolog
- JavaScript "protections" (e.g. `<script>location = top.location</script>`)
- (...)

**Comment by jiamcs** [comment]
Hi!
With the OJS 3.3.0.8  and PKP PN Plugin version 2.0.4.2
The Network Status was "The PKP PLN does not know about this journal yet"
On 7 July we have updated to the latest version OJS 3.3.0.11  and PKP PN Plugin version 2.0.4.2
The Network Status has been changed to "The PKP PLN can accept deposits from this journal"
But nothing is being sent. 
I checked the schedule task logs for the PLN task:

started-
[2022-07-11 22:20:05] http://jiamcs.centre-univ-mila.dz
[2022-07-11 22:20:05] [Notice] Task process started.
[2022-07-11 22:20:05] [Notice] PLN Depositor execute Actions started
[2022-07-11 22:20:05] [Notice] Depositor processing for Journal of Innovative Applied Mathematics and Computational Sciences.
[2022-07-11 22:20:05] [Warning] Your system must have a tar executable.
[2022-07-11 22:20:05] [Notice] Task process stopped.

Which shows the requirement of Archive_Tar extension. However, Archive_Tar and ZIP both already installed on the server. 

I also I found this post  " [Regarding PKP PN Setting & Status](https://forum.pkp.sfu.ca/t/regarding-pkp-pn-setting-status/61928/11)"


that suggest downgrading the PHP version from 7.4 to 7.3 but our PHP version is already 7.3

How could we solve this issue?
Thanks & Regards

**Current OJS version:** 3.3.0.11 (July 7, 2022 - 10:15 AM)
**PN Plugin version:**  2.0.4.2
**PHP version:**    7.3.33
**journal's unique identifier for the PKP PN**: 
 5DEBFCC5-9C51-4FAA-8DF7-A57B22ABE457
[URL: ](http://jiamcs.centre-univ-mila.dz/index.php/jiamcs/index)
![image](https://user-images.githubusercontent.com/109045416/178809085-a19b823b-e0cb-4328-98ea-51c99b88b4da.png)
![image](https://user-images.githubusercontent.com/109045416/178809148-31b39d78-4859-4968-b160-dd1cc3daa470.png)

**Comment by jonasraoni** [comment]
Hi @jiamcs!

**I advise you to post such problems in the forum, so other users might be able to help you faster.** 

According to the error log `[2022-07-11 22:20:05] [Warning] Your system must have a tar executable.`, looks like the plugin couldn't find the `Archive_Tar`, which is a PEAR library.

The next release of the plugin will not require the `Archive_Tar`... But for now, you must ensure that your PHP is configured to include the path where the PEAR libs were installed, using the `include_path` setting of the `php.ini`.

**Comment by jiamcs** [comment]
Hi @jonasraoni ,

The PKPPNDepositorTask file log:

**PKPPNDepositorTask-62d2062cc13ff-20220716.log**
[2022-07-16 00:28:28] [http://jiamcs.centre-univ-mila.dz 1](http://jiamcs.centre-univ-mila.dz/)
[2022-07-16 00:28:28] [Notice] Task process started.
[2022-07-16 00:28:28] [Notice] PLN Depositor executeActions started
[2022-07-16 00:28:28] [Notice] Depositor processing for Journal of Innovative Applied Mathematics and Computational Sciences.
[2022-07-16 00:28:28] [Notice] Getting service document.
[2022-07-16 00:28:31] [Notice] Processing deposit status updates.
[2022-07-16 00:28:31] [Notice] Trying status update for 2 (Issue: 2) (Local Status: [Transferred], Processing Status: [Unknown], Lockss Status: [Unknown])
[2022-07-16 00:28:31] [Notice] Processing status got for 2 → (reserialized)
[2022-07-16 00:28:31] [Notice] Trying status update for 3 (Issue: 3) (Local Status: [Transferred], Processing Status: [Unknown], Lockss Status: [Unknown])
[2022-07-16 00:28:32] [Notice] Processing status got for 3 → (xml-error)
[2022-07-16 00:28:32] [Notice] Deposit 3 has unknown processing state xml-error
[2022-07-16 00:28:32] [Notice] Processing updated content.
[2022-07-16 00:28:32] [Notice] Processing new content.
[2022-07-16 00:28:32] [Notice] Packaging content for deposit.
[2022-07-16 00:28:32] [Notice] Trying package deposit 1 (Issue: 1) (Local Status: [New], Processing Status: [Unknown], Lockss Status: [Unknown])
[2022-07-16 00:28:33] [Notice] Native Import/Export plugin failed for deposit 1, when trying to package it

At the same time the messages from our server/PHP error log 

**Server/PHP error log**
[Sat Jul 16 00:28:32.702900 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/11/61ccd59c1f85f.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:32.903788 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/6/61cd0fc48ec35.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:32.974083 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/5/61cc414a4288b.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:32.978976 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/5/61cc414a4288b.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:32.984008 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/5/61cc46660cdf9.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:32.984043 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/5/61cc42f415c21.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:33.071541 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/4/61ccf9cd0b60f.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:33.130602 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/2/61cdab5b558ca.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:33.135740 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: filesize(): stat failed for www/jiamcs/ojs/jiamcsfiles/journals/1/articles/2/61cdaf9f6604e.pdf in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 142
[Sat Jul 16 00:28:33.139878 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: DOMElement::setAttribute() expects parameter 2 to be string, array given in
www/jiamcs/ojs/lib/pkp/plugins/importexport/native/filter/PKPPublicationNativeXmlFilter.inc.php on line 89
[Sat Jul 16 00:28:33.164813 2022] [php7:notice] [pid 27205] [client 196.89.142.38:57091] PHP Notice: Trying to get property ‘documentElement’ of non-object in www/jiamcs/ojs/plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
on line 204
[Sat Jul 16 00:28:33.167843 2022] [php7:warn] [pid 27205] [client 196.89.142.38:57091] PHP Warning: Cannot modify header information - headers already sent in www/jiamcs/ojs/lib/pkp/classes/plugins/ImportExportPlugin.inc.php on line
170


![image](https://user-images.githubusercontent.com/109045416/179624542-08c01b70-8072-4a80-9fbf-041ca46ba1a5.png)


Thanks,

**Comment by jonasraoni** [comment]
The main issue is the number of records being processed at once. It's needed to do some partitioning, and stop pinging often journals that have been unresponsive for too long.
